sudo: false
language: node_js
notifications:
  email: true
node_js:
  - "10"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
script:
  yarn test
env: 
  CODECOV_TOKEN=74d19184-dc30-4935-a0cf-a8945bd3884b
after_success:
  - codecov